[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "e"
run  = "open"
desc = "Open to edit"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Open to edit"

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "Lazygit"

[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
run  = 'shell --block -- transform "$0"'
desc = "transform"
